In [66]:
import pandas as pd
import numpy as np

In [2]:
car=pd.read_csv(r"D:\Datasets\quikr_car.csv")
car

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [3]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [4]:
car.shape

(892, 6)

In [5]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [6]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [7]:
car['Price']

0             80,000
1           4,25,000
2      Ask For Price
3           3,25,000
4           5,75,000
           ...
887         3,10,000
888         2,60,000
889         3,90,000
890         1,80,000
891         1,60,000
Name: Price, Length: 892, dtype: object

In [8]:
car['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [9]:
 car['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

# Cleaning

In [10]:
backup=car.copy()

In [11]:
car=car[car['year'].str.isnumeric()]

In [12]:
car['year']=car['year'].astype(int)

C:\Users\dibya\AppData\Local\Temp\ipykernel_4748\152728128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  car['year']=car['year'].astype(int)

In [13]:
car=car[car['Price']!="Ask For Price"]
#car=car[car['Price']!='Ask For Price']

In [14]:
car['Price']=car['Price'].str.replace(',','').astype(int)

In [15]:
car['kms_driven']=car['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [16]:
car=car[car['kms_driven'].str.isnumeric()]

In [17]:
car['kms_driven']=car['kms_driven'].astype(int)

In [18]:
car[car['fuel_type'].isna()]

               name company  year   Price  kms_driven fuel_type
132  Toyota Corolla  Toyota  2009  275000       26000       NaN

In [19]:
car=car[~car['fuel_type'].isna()]

In [20]:
car['name']=car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [21]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
6                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
885          Tata Indica V2      Tata  2009  110000       30000    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
888            Tata Zest XM      Tata  2018  260000       27000    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [22]:
#if u want to reset the index--:
#car.reset_index(drop=True)

In [23]:
car[car['Price']>6e6]

                   name   company  year    Price  kms_driven fuel_type
562  Mahindra XUV500 W6  Mahindra  2014  8500003       45000    Diesel

In [24]:
car=car[car['Price']<6e6].reset_index(drop=True)

In [25]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [26]:
car.to_csv('Cleaned car.csv')

# Model

In [27]:
X=car.drop(columns='Price')
y=car['Price']

In [29]:
X

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [30]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int32

In [49]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [50]:
ohe=OneHotEncoder()
ohe.fit(X[['name','company','fuel_type']])

OneHotEncoder()

In [51]:
ohe.categories_
#ohe.categories

[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
        'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
        'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
        'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
        'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
        'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
        'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
        'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
        'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
        'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
        'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
        'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
        'Ford EcoSport Titanium', 'Ford EcoSport Trend',
        'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
        'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
        'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
        'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
        'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
        'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
        'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
        'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
        'Hyundai Accent Executive', 'Hyundai Accent GLE',
        'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
        'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
        'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
        'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
        'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
        'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
        'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
        'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
        'Hyundai Verna Transform', 'Hyundai Verna VGT',
        'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
        'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
        'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
        'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
        'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
        'Land Rover Freelander', 'Mahindra Bolero DI',
        'Mahindra Bolero Power', 'Mahindra Bolero SLE',
        'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
        'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
        'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
        'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
        'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
        'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
        'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
        'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
        'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
        'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
        'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
        'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
        'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
        'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
        'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
        'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
        'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
        'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
        'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
        'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
        'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
        'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
        'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
        'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
        'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
        'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
        'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
        'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
        'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
        'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
        'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
        'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
        'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
        'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
        'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
        'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
        'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
        'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
        'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
        'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
        'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
        'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
        'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
        'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
        'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
        'Volkswagen Passat Diesel', 'Volkswagen Polo',
        'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
        'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
        'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
        'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [52]:
column_trans=make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),remainder='passthrough')

In [53]:
lr=LinearRegression()

In [54]:
pipe=make_pipeline(column_trans,lr)

In [55]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [56]:
y_pred=pipe.predict(X_test)

In [57]:
y_pred

array([ 314073.19146738,  593236.79232971,  471573.56107225,
         72849.87037463,  313192.35989696,  658342.88659088,
        382920.56073758,  297679.54086998,  430615.93305354,
        288225.75842787,  671394.03274807,  576629.76332364,
        304879.33123378,  717759.81026279,  315340.18646669,
        374697.86484918,  622834.11298197,  -48381.36526887,
        567960.31590836,  432998.61274362,  248653.58584868,
        451247.6771737 ,  165451.35214476,  495947.11542371,
        117249.52579492,  566795.81662102,  565948.28869811,
        568408.19603429,  288651.2381387 ,  626205.34856024,
        361067.81835878,  170582.52350473,  576629.76332364,
        222338.25119285,  290138.42988037,  212651.35663041,
        212702.56381556,  612890.07809378,  277049.48557066,
        219121.4734124 ,  472573.81752383,  -69891.20823179,
       -187829.51701734,   52119.24861664,  232218.28506926,
        619512.9870429 ,  183891.52883818,  344336.0770764 ,
        491613.74974418,  160501.60504426,  305712.17164253,
        222305.91156841,  517637.17972738,  239831.58996443,
         73661.57929133,  347793.9730643 ,  241723.5880276 ,
        521768.25168592,  483647.75212993,  199764.49847165,
        772719.48739386,   48338.09988395,  318879.98382388,
        345022.65526263,  517963.61471273,  218379.5415648 ,
        283049.36819661,  441223.79357567,  156335.37498908,
        260265.3837081 ,  362723.34222229,   42687.24284337,
        234981.11687105, 1753244.07502526,  318544.63843678,
        558082.03211552,  237452.12830453,  610715.66600237,
        719009.34007836,  281543.24518543,  261707.66793722,
        115904.29777537,   71881.94698314, 2197315.49742071,
        142723.14162573,  478229.35686015,  490898.91353529,
        421673.71061841,  197795.32577153, 1490932.09326629,
        369063.2879335 ,   63496.27461401,    4775.9860377 ,
        786705.63073109,  336797.81053893,  240918.47943148,
        594363.54419822,  562921.64327117,  271368.01164331,
        447308.84435226,  197795.32577153,  285348.61435288,
        166275.25949354,  -67897.98447333,  370318.75056809,
        227862.76301647,  235100.78724132,  563357.09362404,
        492903.83369324,  608826.62592664,  413393.08797087,
        198022.56019609,  419502.3822251 ,  643842.88380199,
        571887.42120457,  650803.10472645,  848443.72211575,
        376361.22123603,  140803.18202524,  388727.95515867,
        450670.11538672,  455513.92808814,  623011.58406237,
        553587.05134449,  465863.09467422,  157229.21182211,
        369063.2879335 ,  183891.52883818,   72443.81957951,
        297153.82683656,  380809.6322583 ,  132231.9975648 ,
        283049.36819661,  702476.41750359,  149622.37355724,
        591385.09353749,  188324.45476186,  542474.50802993,
        633495.91373355,  348059.7557404 ,  102416.14056317,
        559415.06870344,  379949.69127109,  171446.26555096,
        744055.78538962,  261538.53569885,  266186.59740657,
        420626.12741786,  339572.49107776,  127821.28070188,
        107135.81906009,  892122.37090614,  423797.61643779,
        530758.51156678,  524819.01083153,  456753.11723201,
        325362.98177645,   86334.81268773,  870771.21224375,
        133305.91008081,  235005.99067511,  234668.86711729,
         91571.32032936])

In [59]:
r2_score(y_test,y_pred)

0.6870783485437679

In [86]:
score=[]
for i in range(800):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    print(r2_score(y_test,y_pred),i)
    score.append(r2_score(y_test,y_pred))

0.6726406851590235 0
0.5151038941280177 1
0.4977488228081809 2
0.6323522594540925 3
0.5557622827522763 4
0.6750472338126494 5
0.6611821331641934 6
0.539041932325443 7
0.5115111383027224 8
0.7180388493261676 9
0.7060038629064057 10
0.7702539926937939 11
0.6725283509026667 12
0.603069457593584 13
0.6238718622083012 14
0.5326124360431036 15
0.6701980361236111 16
0.5952686541953816 17
0.4380932662624285 18
0.7498078427445969 19
0.5837325922865015 20
0.573789772082752 21
0.5928889258822889 22
0.7310052585130424 23
0.6785216487151209 24
0.4313868608847836 25
0.6724619273686687 26
0.5558924259034865 27
0.7481951401480293 28
0.7292614050879783 29
0.6377741220443762 30
0.7290818306051152 31
0.7116352149763614 32
0.6993161244972665 33
0.6234917719249626 34
0.6783202391395393 35
0.6032516808162844 36
0.6681545407654303 37
0.5431120015865782 38
0.6780556219473312 39
0.7175186035117227 40
0.7011647017349902 41
0.6636824537593129 42
0.4917435219539842 43
0.6932695589718791 44
0.718022735284519 45
0.7732129624171924 46
0.6184621355903093 47
0.5425844451310093 48
0.7172489989310609 49
0.6778903101868442 50
0.7259634340000594 51
0.7215630442864014 52
0.5055130613092691 53
0.649141348752815 54
0.7029854938413252 55
0.6749573091298418 56
0.572625403762882 57
0.6821609884944245 58
0.7487337763844049 59
0.5254017610311068 60
0.5589624187364206 61
0.7591979401517571 62
0.774819533956984 63
0.7055106318943858 64
0.7063942005378155 65
0.7167265759165857 66
0.7100902758459611 67
0.6116282467099148 68
0.6053922236480451 69
0.6951340337281253 70
0.6662031750876132 71
0.6069653808731725 72
0.7465176308254398 73
0.7570562677255184 74
0.7579691827813128 75
0.6845934033130756 76
0.6495154515814543 77
0.7160268852936786 78
0.6825368306388278 79
0.5853116143696577 80
0.6482358989057293 81
0.7724160254039376 82
0.5256014989961835 83
0.5699193102241328 84
0.6077475608746647 85
0.7100875491997864 86
0.6667080418658141 87
0.6726779372164344 88
0.6029309863311755 89
0.7033141487413282 90
0.6355388244696415 91
0.70242497349544 92
0.692510338431665 93
0.5142523951745461 94
0.589769352000334 95
0.6329475610413247 96
0.7220786443964715 97
0.6956002960857469 98
0.5148307358465929 99
0.52690146485332 100
0.6572666762573309 101
0.6720737007120516 102
0.7045169735864742 103
0.648351379028476 104
0.6108819406743479 105
0.7274623888009875 106
0.697083034172816 107
0.6880730978347198 108
0.7343352468199944 109
0.7316836003427195 110
0.6942060380854556 111
0.7460217065901731 112
0.6035696235310908 113
0.4529291241806309 114
0.5603347312274983 115
0.6237478978669017 116
0.7553319269673877 117
0.6010547779250577 118
0.7231871951291204 119
0.7412030083620433 120
0.7214810542161525 121
0.6803770756861292 122
0.7262390009409069 123
0.5339402167510003 124
0.5627754713760298 125
0.6268889085621234 126
0.6482497580562947 127
0.643161126262006 128
0.678547339775905 129
0.6003303624279841 130
0.7374728473896938 131
0.7238564098000009 132
0.7222564958218026 133
0.5640090493333257 134
0.49975988381104375 135
0.6632080358418011 136
0.5239736088290117 137
0.774284399689954 138
0.649098581534229 139
0.7177532944976893 140
0.7808226239920042 141
0.4741872594271025 142
0.6134509741071996 143
0.582916222113131 144
0.6554832581025913 145
0.6523909246581107 146
0.6621631935979795 147
0.695321184514548 148
0.5883556870957045 149
0.705182016851707 150
0.5951084816809568 151
0.5350623207299559 152
0.49619411980850414 153
0.5932136340262568 154
0.6558971570575718 155
0.6685962649990246 156
0.5859930848738972 157
0.6064779392738302 158
0.6932521917211255 159
0.6946747834742208 160
0.6304840916136799 161
0.728589087814965 162
0.7138135875420653 163
0.4699207782687136 164
0.7525404561851132 165
0.6760491461982718 166
0.5984580531055816 167
0.5703177988388644 168
0.6275715321338224 169
0.7484909902029548 170
0.6979751623040957 171
0.48059379513010303 172
0.7001201633812802 173
0.695155569097343 174
0.48069870034790585 175
0.47222418190313487 176
0.6194194282738565 177
0.6898559890160305 178
0.7436549418064196 179
0.679870213030443 180
0.6737951019242073 181
0.5263202288885933 182
0.5968798470596761 183
0.5684333458670041 184
0.740390525970613 185
0.7645668645219841 186
0.6951529373264593 187
0.5865094216884335 188
0.6781224925442526 189
0.5926546551317431 190
0.76163668709807 191
0.678844223975272 192
0.621722671584702 193
0.6392765000766238 194
0.5181446846950828 195
0.7157691760713567 196
0.7184324002827526 197
0.6308592330281845 198
0.7113171026934815 199
0.420100171650336 200
0.6710068807611608 201
0.6750271088304227 202
0.6407107524171812 203
0.6877127897577036 204
0.7207710263859904 205
0.5251180239750143 206
0.7240272613776304 207
0.6870799210800145 208
0.673088648195789 209
0.5141662560753673 210
0.7073597431400918 211
0.5440644637094499 212
0.4712212509133318 213
0.6738933960869213 214
0.6393966244345266 215
0.7848912142053415 216
0.6723305905316455 217
0.6706060167491237 218
0.6428152103708646 219
0.5689689878921851 220
0.6924745298199717 221
0.4554472237042181 222
0.683239668809112 223
0.6029796695362204 224
0.8427911715197592 225
0.46864522019356547 226
0.5575728877912449 227
0.694006099245046 228
0.7581658442594791 229
0.7837662311796347 230
0.4974254682032532 231
0.5950836442768374 232
0.5872900577993287 233
0.7180662994439576 234
0.7708662258121205 235
0.5193016092028746 236
0.46027709479145806 237
0.535702359726342 238
0.5579281373991702 239
0.6151028637923015 240
0.6856764037548525 241
0.6484016593377652 242
0.6654339498058515 243
0.5681334584604955 244
0.6883157934218422 245
0.6610849134858179 246
0.6088750555695042 247
0.6945084124025268 248
0.6529309726842492 249
0.72386436899943 250
0.637188151931642 251
0.593431395962094 252
0.4677082781528774 253
0.7623957643677097 254
0.6181762217899016 255
0.8019334408999701 256
0.6347626859840807 257
0.6914689019271824 258
0.7321535557630958 259
0.7048659738656806 260
0.63384783211326 261
0.6981033764865132 262
0.6072605116371382 263
0.6168694446823115 264
0.6931307712764229 265
0.747176538504122 266
0.5387694281964174 267
0.49944315680089324 268
0.7093242922393717 269
0.3598017760490684 270
0.5812344533290643 271
0.5717654788155162 272
0.6455816173911564 273
0.7263953143983133 274
0.5457646426367303 275
0.6572090086353043 276
0.5293332759263034 277
0.5272208534289009 278
0.6701945660438711 279
0.5792133660916843 280
0.5048830044167504 281
0.4649088597540756 282
0.682190229166401 283
0.539246819392363 284
0.7231659451385324 285
0.639463141956808 286
0.6963547038846257 287
0.6431280427676707 288
0.5257147355064382 289
0.7954161630338901 290
0.7023766652103581 291
0.6189544698440882 292
0.42114591806443313 293
0.5402046290550486 294
0.5926640163563319 295
0.6962716046454711 296
0.4797734754383811 297
0.6561868681564746 298
0.6073350613125614 299
0.6152586841027705 300
0.6207603131472997 301
0.6285862940701372 302
0.6689216864314261 303
0.7235154386555479 304
0.6295897113460439 305
0.6991967522800882 306
0.6724126815280322 307
0.4884814967577741 308
0.6295797150632338 309
0.6575168462625764 310
0.7609919060208878 311
0.7686870419863147 312
0.5945952288833289 313
0.5123371855513469 314
0.6670154772154435 315
0.7397145911078631 316
0.6179603268892867 317
0.6792723023738735 318
0.5374141451700538 319
0.6608737337060071 320
0.7039918769192828 321
0.8085314377086663 322
0.53735104983076 323
0.6454335980340677 324
0.6521110756445637 325
0.6587798044882139 326
0.5764581358624301 327
0.6105603843789205 328
0.6820787397680796 329
0.641763359625148 330
0.6477035814916419 331
0.6629174759001757 332
0.562876281482281 333
0.47884441126186594 334
0.5717453053621808 335
0.5804570469110163 336
0.7018963585055171 337
0.617354578725247 338
0.7571172278648933 339
0.6504806374433965 340
0.6562639015896493 341
0.742951064498034 342
0.7818502258106429 343
0.49634238009242126 344
0.565676099335181 345
0.5994501679033026 346
0.6626259250793004 347
0.6757765724190081 348
0.6829666762996914 349
0.6248267587334091 350
0.711920578040236 351
0.5306909785565955 352
0.7627499595212848 353
0.5148352692332175 354
0.687520569386146 355
0.7518686996553163 356
0.6514471876550696 357
0.736480201691281 358
0.5235476565598995 359
0.54844451903942 360
0.6053020211317952 361
0.6862989638772479 362
0.7302702882092387 363
0.5059155833693691 364
0.6359737123604563 365
0.6915201286448975 366
0.6351289353014504 367
0.7305915844327 368
0.6420417675834644 369
0.6585559815925328 370
0.735546487227501 371
0.6404825401914156 372
0.6964973003575048 373
0.6581856477602592 374
0.6914691810915685 375
0.6435012084324346 376
0.48934310872867715 377
0.697356651491242 378
0.7847362536833477 379
0.6009967124256655 380
0.7687961896644463 381
0.7572561746553204 382
0.6586895609802836 383
0.6399233773313162 384
0.6445538384986642 385
0.4856842246496813 386
0.623431109207673 387
0.5969005234444056 388
0.7087918505043803 389
0.6140360329056178 390
0.6346423035097009 391
0.7598128883538725 392
0.6741459278071688 393
0.5524930883008015 394
0.7440787411824943 395
0.6473128607560779 396
0.7596884609431054 397
0.6558770433658763 398
0.591977211370045 399
0.7774573164030846 400
0.7349837323398378 401
0.6236318392399194 402
0.4987695669995733 403
0.695286852621477 404
0.6945056865991736 405
0.5285833793161673 406
0.613312658044042 407
0.5196422278333548 408
0.762652219520556 409
0.6246602087318913 410
0.6598331787035285 411
0.7541179260354756 412
0.7296579565448366 413
0.6095148146223195 414
0.6378288071154897 415
0.7312105589888491 416
0.635780498088673 417
0.5344427761896033 418
0.723973095153964 419
0.5306675393472384 420
0.5691171991456805 421
0.7207993955247948 422
0.6618464634293741 423
0.6524185477431987 424
0.7376668338165875 425
0.5837393150503298 426
0.6097251381744805 427
0.6910495787470603 428
0.5490610950888506 429
0.6902838288135091 430
0.6180786956388591 431
0.686978723980153 432
0.7423561210154023 433
0.7197060601170956 434
0.6743207745738917 435
0.5688429794578924 436
0.7555960660663202 437
0.6885654370581846 438
0.7149413754475553 439
0.5580069843905899 440
0.537809169155038 441
0.7253452341033566 442
0.638442651996966 443
0.4940799315810869 444
0.52769289681 445
0.5591494405805725 446
0.6087398244541844 447
0.6458944004980732 448
0.5853235353384468 449
0.6456583128075298 450
0.6192314313353933 451
0.6682253864383233 452
0.5420467337023278 453
0.6771944404275675 454
0.5129373932555352 455
0.663716249728038 456
0.6986170155342233 457
0.652916212812803 458
0.5296987320695093 459
0.693669946818017 460
0.6745448635824137 461
0.5963523958280181 462
0.7864969636939604 463
0.676876985898187 464
0.6532461735748003 465
0.7283493368035792 466
0.6455176915961505 467
0.3903658289456997 468
0.607789611421135 469
0.6977500983762577 470
0.6431570551067544 471
0.7608958534190985 472
0.48041204257103964 473
0.6682484642820012 474
0.7176291236754089 475
0.6692122474816004 476
0.5614762054967248 477
0.6802761285139783 478
0.7689036569776445 479
0.797168178790713 480
0.5222001187249339 481
0.6691164127639947 482
0.7760682598289127 483
0.7120092047110619 484
0.7564649229758982 485
0.5199656023701421 486
0.5149727142555078 487
0.5819993296200854 488
0.5311368537065025 489
0.46114817955720866 490
0.6152313416394657 491
0.7224480530136241 492
0.7150361531287905 493
0.620904777282165 494
0.5025259378634219 495
0.6554979480844181 496
0.5944902412175082 497
0.6487410786380655 498
0.6069803046667905 499
0.5092852584014523 500
0.7306786753932404 501
0.6013044272056276 502
0.6413964565404136 503
0.6841748265954277 504
0.6532305146584595 505
0.5398511335829835 506
0.7312579145498215 507
0.723731103386034 508
0.6159562130146172 509
0.6172327852064157 510
0.6748791193790556 511
0.6416303785381506 512
0.6289459014812208 513
0.7459822923035038 514
0.6885697438466867 515
0.6459249195513905 516
0.708504612401169 517
0.6641056483246178 518
0.7268574240445298 519
0.700011639145555 520
0.6975883534820885 521
0.6331394952133899 522
0.7395105018082314 523
0.5915635988852412 524
0.5757048372260962 525
0.7707924370235815 526
0.6438755955615085 527
0.5527083670904605 528
0.5022509660645107 529
0.7341777378172254 530
0.47945234877572773 531
0.7319235603473173 532
0.6727585485628083 533
0.640455093355181 534
0.6594449246617982 535
0.6184402872146435 536
0.6187126629584971 537
0.6510216789106318 538
0.7130473098278222 539
0.6779037789616063 540
0.566029038721034 541
0.6540271658992121 542
0.7167414570277915 543
0.587523278536108 544
0.6449635052094187 545
0.5380781106976009 546
0.5244175539353971 547
0.7668700981951532 548
0.5784629781322577 549
0.5574222212838892 550
0.5397196584972799 551
0.4912127874611001 552
0.5083768410262337 553
0.6761840318157375 554
0.4169059681179835 555
0.8027710246541097 556
0.5220102302066685 557
0.5092735974304303 558
0.6436712857708795 559
0.5861884648455183 560
0.7614175808787427 561
0.5479518450384953 562
0.6971630984260591 563
0.7000336281547801 564
0.5637688508928292 565
0.6592727081701537 566
0.6897865563729779 567
0.5866093294332544 568
0.571891517099876 569
0.6230908986340087 570
0.7522515552826469 571
0.700060668450842 572
0.5982447956095223 573
0.5452861269414813 574
0.7425584396153981 575
0.4800843825171176 576
0.5865167485044289 577
0.6969778415377041 578
0.7570157681253148 579
0.5115052457338481 580
0.6806174688941341 581
0.6879593940005148 582
0.6736440574385391 583
0.6379394991882295 584
0.5394233560517238 585
0.6385500759299061 586
0.5787624572850341 587
0.7105536501082086 588
0.4795297325403388 589
0.6747581688779325 590
0.6134416454544087 591
0.5826154476194246 592
0.6587303167642053 593
0.553794532076065 594
0.6011020312841324 595
0.7349125134336495 596
0.6903769621094127 597
0.37829854749963143 598
0.588495022094562 599
0.6499245155948481 600
0.6917707576308573 601
0.6734629722523362 602
0.5827689649496779 603
0.626740433857604 604
0.5822623145548961 605
0.6967006647707608 606
0.5766946833713136 607
0.30299167711387787 608
0.6531440864595779 609
0.7329158739599961 610
0.49622939858854087 611
0.5952357542339823 612
0.7080404826357288 613
0.622158068149715 614
0.677336085375996 615
0.6313292166727359 616
0.6999680560988304 617
0.7273899533411656 618
0.6739004539912132 619
0.598886110680751 620
0.6539526527869475 621
0.7354998935826393 622
0.6281452592377363 623
0.7089331014764328 624
0.6911921481564731 625
0.7056046047791189 626
0.6754383062907807 627
0.7274303831998092 628
0.6488662930886948 629
0.527909468920662 630
0.549400582344902 631
0.6054139875320725 632
0.7496613143340529 633
0.7086991781824498 634
0.6062712832155284 635
0.7026138524034536 636
0.754407711515187 637
0.6019523313257711 638
0.6822123790443941 639
0.5037524968976556 640
0.6050227767146059 641
0.7252750092365737 642
0.5984214625210971 643
0.5119969146051103 644
0.5990270468836105 645
0.7453649000348104 646
0.6435292588411623 647
0.614710862062946 648
0.6162473592432592 649
0.5415066473822473 650
0.5976547169160707 651
0.8182367753556151 652
0.7733952204811194 653
0.7140477047959959 654
0.7068373949377429 655
0.6213385338755866 656
0.6212046142035799 657
0.5605888259338203 658
0.5638720888456141 659
0.7930228293525761 660
0.6251098454990125 661
0.5480386220067583 662
0.5862466279464528 663
0.7535835242892186 664
0.618167241358713 665
0.717765937422002 666
0.6404858735795428 667
0.7836462705187386 668
0.656724202703993 669
0.5597600640488261 670
0.579362606458091 671
0.6993657305588086 672
0.7502173906784851 673
0.672511397645621 674
0.7302689026006817 675
0.639644664331722 676
0.3940207865339197 677
0.5625915022785417 678
0.6926713952100674 679
0.5674318094676309 680
0.539072660342286 681
0.5131631802272628 682
0.7510184889324408 683
0.5866354963044249 684
0.7401256822269842 685
0.6833973008628366 686
0.6656852264416049 687
0.6003441438531403 688
0.8007561051552748 689
0.6496689339019023 690
0.6814280817845961 691
0.6401384528254173 692
0.6028922519866036 693
0.6696000981427741 694
0.6407165530234981 695
0.7014709020033392 696
0.6361088113215925 697
0.7729392994884479 698
0.48719618838234047 699
0.5678834116807434 700
0.48992912037388414 701
0.6068240731206564 702
0.6987869932301011 703
0.6025868387419013 704
0.6203209961323861 705
0.4358361457397475 706
0.5462399516602643 707
0.6277127734718061 708
0.5900072956305171 709
0.8397646107961191 710
0.5569879140347399 711
0.5549163788389659 712
0.6779953878372356 713
0.684241565442997 714
0.6658641634857941 715
0.5627100385379711 716
0.6645991838902064 717
0.598744753107119 718
0.6406185318244355 719
0.5572838689221267 720
0.7068911280702117 721
0.7219705983117446 722
0.649776389645145 723
0.5908369203755679 724
0.5211514323564379 725
0.5624758537389192 726
0.6596771488232691 727
0.5172890967484899 728
0.7442217862174058 729
0.7310367971521956 730
0.636203452880544 731
0.6075093673979409 732
0.5840238522523504 733
0.6776347236049052 734
0.6853878913066072 735
0.6744957852217148 736
0.7287085247134772 737
0.5090807818553398 738
0.6399928340588023 739
0.6762000394284549 740
0.5315434958928151 741
0.5830689250062079 742
0.6215785581055742 743
0.5260074361128997 744
0.8064052407014721 745
0.6670599285566581 746
0.5774532121101307 747
0.7641580314500005 748
0.6770485747265793 749
0.6736605517092482 750
0.6830931573201435 751
0.6781948574547417 752
0.7607101049782542 753
0.7620937325199554 754
0.6400927824971511 755
0.6088468565678486 756
0.5211157130471421 757
0.6669922211900574 758
0.590382980249498 759
0.6191263828590073 760
0.5875964459065326 761
0.7306820326568688 762
0.6393304241447298 763
0.6494185309465527 764
0.5504356605152239 765
0.5797607066607093 766
0.4255118410604787 767
0.6722427553975414 768
0.6915183722938879 769
0.5783293959477978 770
0.6432717192635224 771
0.6723494158494954 772
0.5830235553089306 773
0.6786604614839815 774
0.7316670085064327 775
0.627925809103961 776
0.6300382170047749 777
0.5920347929781707 778
0.644996661034257 779
0.6099511438653482 780
0.7053611964146949 781
0.5712325514597504 782
0.6712417481715198 783
0.6844086290243048 784
0.6218281418933798 785
0.6411021440025602 786
0.716932642360436 787
0.5236811902377454 788
0.6488438963482868 789
0.7006232872662506 790
0.6353832526719758 791
0.5736771427437191 792
0.6380092364490915 793
0.5960308126751896 794
0.6173591110358507 795
0.6430932750031918 796
0.6175243459432498 797
0.5954263732998865 798
0.5335426348110769 799

In [87]:
np.argmax(score)

225

In [88]:
score[np.argmax(score)]

0.8427911715197592

In [89]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=np.argmax(score))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.7244313817030879

In [90]:
import pickle

In [91]:
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))#open in write binary mode

In [93]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']],columns=['name','company','year','kms_driven','fuel_type']))

array([451590.51436178])